export const CIRCUITS = {
  essandilene: {
    slug: "essandilene",
    title: "Essandilène & Oasis d'Ihrrir",
    tagline: "Au cœur du Tassili, entre guelta cristalline et palmeraie cachée",
    duration: "8 jours / 7 nuits",
    difficulty: "Modérée",
    group: "4 à 10 voyageurs",
    priceFrom: 1450,
    hero: "/pics/circuit-essandilene-1.jpg",
    gallery: [
      "/pics/circuit-essandilene-1.jpg",
      "/pics/circuit-essandilene-2.jpg",
      "/pics/circuit-essandilene-3.jpg",
    ],
    description:
      "Une expédition contemplative dans le Tassili n'Ajjer : trekking entre cathédrales de grès, baignade dans la guelta d'Essandilène, nuits à la belle étoile dans l'oasis perdue d'Ihrrir, et rencontres authentiques avec les guides Touaregs qui connaissent chaque pierre du désert.",
    highlights: [
      "Guelta d'Essandilène : oasis d'eau pure entre les falaises",
      "Oasis d'Ihrrir : palmeraie isolée, refuge ancestral des Kel Ajjer",
      "Peintures rupestres préhistoriques et gravures néolithiques",
      "Nuits sous la voie lactée, bivouacs au pied des dunes",
      "Repas traditionnels Touaregs : taguella, méchoui, thé à la menthe",
    ],
    itinerary: [
      { day: "Jour 1", title: "Arrivée à Djanet", text: "Accueil à l'aéroport Tiska, installation, briefing de l'expédition autour d'un thé." },
      { day: "Jour 2", title: "Djanet → Tikoubaouine", text: "Départ en 4x4, traversée des premiers paysages lunaires, premier bivouac." },
      { day: "Jour 3", title: "Vers Essandilène", text: "Trek modéré entre les arches naturelles, baignade dans la guelta." },
      { day: "Jour 4", title: "Oasis d'Ihrrir", text: "Découverte de la palmeraie cachée, repas partagé avec les habitants." },
      { day: "Jour 5", title: "Sites rupestres", text: "Visite guidée des fresques préhistoriques classées UNESCO." },
      { day: "Jour 6", title: "Erg de sable doré", text: "Après-midi dans les dunes, coucher de soleil et nuit en bivouac libre." },
      { day: "Jour 7", title: "Retour vers Djanet", text: "Dernière journée de désert, soirée musicale Touareg." },
      { day: "Jour 8", title: "Départ", text: "Transfert vers l'aéroport et envol." },
    ],
    included: [
      "Tous les transferts en 4x4 avec chauffeur expérimenté",
      "Guide Touareg francophone diplômé",
      "Pension complète (eau, repas, thé)",
      "Matériel de bivouac (tapis, couvertures)",
      "Permis et autorisations parc national",
    ],
    notIncluded: [
      "Vols internationaux et domestiques",
      "Visa algérien et assurance voyage",
      "Boissons supplémentaires et pourboires",
    ],
  },
  tadrart: {
    slug: "tadrart",
    title: "Tadrart Rouge",
    tagline: "Le plus beau désert du monde — cathédrales de grès et dunes infinies",
    duration: "10 jours / 9 nuits",
    difficulty: "Soutenue",
    group: "4 à 8 voyageurs",
    priceFrom: 1850,
    hero: "/pics/circuit-tadrart-1.jpg",
    gallery: [
      "/pics/circuit-tadrart-1.jpg",
      "/pics/circuit-tadrart-2.jpg",
      "/pics/circuit-tadrart-3.jpg",
    ],
    description:
      "L'expédition signature de Djanet Étoile. Plongée totale dans la Tadrart, joyau minéral où les ergs aux teintes ocre rougeoient au lever du soleil. Dix jours d'immersion, du Tassili au cœur du Tadrart, sur les traces des caravanes Kel Ajjer.",
    highlights: [
      "Erg Admer : océan de dunes rouges au coucher du soleil",
      "Arches de Tin Merzouga, monolithes sculptés par le vent",
      "Gravures rupestres millénaires de la période bovidienne",
      "Bivouacs au cœur de cathédrales de grès",
      "Rencontres et veillées dans les campements nomades",
    ],
    itinerary: [
      { day: "Jour 1", title: "Arrivée à Djanet", text: "Accueil, installation, briefing." },
      { day: "Jour 2", title: "Djanet → Erg Admer", text: "Première traversée, dunes au coucher du soleil." },
      { day: "Jour 3", title: "Tin Merzouga", text: "Exploration des arches, photographie au lever du jour." },
      { day: "Jour 4", title: "Vallée de l'Oued Imehrou", text: "Trek dans le canyon, gravures préhistoriques." },
      { day: "Jour 5", title: "Cathédrales de grès", text: "Marche entre les monolithes, bivouac protégé." },
      { day: "Jour 6", title: "Tin Tehoudaye", text: "Site de gravures rupestres exceptionnelles." },
      { day: "Jour 7", title: "In Djaren", text: "Dunes orange et silence absolu." },
      { day: "Jour 8", title: "Boucle vers le Sud", text: "Dernière immersion totale, nuit étoilée." },
      { day: "Jour 9", title: "Retour à Djanet", text: "Soirée festive Touareg, hammam." },
      { day: "Jour 10", title: "Départ", text: "Transfert vers l'aéroport." },
    ],
    included: [
      "4x4 et chauffeur expérimenté",
      "Guide Touareg francophone diplômé",
      "Pension complète + thé traditionnel",
      "Matériel de bivouac et logistique complète",
      "Permis et autorisations",
    ],
    notIncluded: [
      "Vols internationaux et domestiques",
      "Visa et assurance voyage",
      "Pourboires et achats personnels",
    ],
  },
};

export const CIRCUITS_LIST = Object.values(CIRCUITS);
